### ISSUE TITLE
[Suggestion] - Tps alerter [NextUpdate]

### ISSUE THREAD

**Issue by TymekSL** [Niix-Dan/StatusCord#1]
### 💡 Suggestion

I think good idea will be when there is tps alerter to the discord. THis will work when server have low than X tps (setupped in the cofig) will receive alert webhook to discord & ingame 

### 🎯 Benefits

Tps alerter

**Comment by Niix-Dan** [comment]
Thank you for the suggestion! That's a great idea. I'll be sure to include it in the next update. ;D
